version: '3.8'

services:
  app:
    build: .
    ports:
      - "9091:9091"  # Mapea 9091 host a 9091 container
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge